from src.Controller.controller_json import read_json

json = [{"id": "5fbbf814600c3906504ee1c5", "customId": None, "name": "LIQUID GAMING LIMITED", "code": "00247079999",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "",
         "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Italia",
                         "countryCode": "IT", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbf72c15ef4f18757cc77e", "customId": None, "name": "AMAZON EU SARL, SUCCURSALE ITALIANA",
         "code": "08973230967", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000047, "name": "AMAZON EU SARL, SUCCURSALE ITALIANA"},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Italia",
                         "countryCode": "IT", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0}, {"id": "5f6230cebfd8f067205fe801", "customId": None, "name": "JOS\u00c9 DAVID TRAPERO DIAZ",
                          "code": "15481509W", "tradeName": 0, "email": "j.david.industrial@gmail.com",
                          "mobile": "637402497", "phone": "", "type": "supplier", "iban": "", "swift": "",
                          "groupId": "", "clientRecord": 0,
                          "supplierRecord": {"num": 40000025, "name": "Jose David Trapero Diaz"},
                          "billAddress": {"address": "C\/ABAR\u00c1N", "city": "SAN JAVIER", "postalCode": "30730",
                                          "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                                          "info": ""}, "customFields": [],
                          "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0,
                                       "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                                       "salesTax": [], "purchasesTax": []},
                          "socialNetworks": {"website": "www.penberic.es"}, "tags": [], "notes": [],
                          "contactPersons": [], "shippingAddresses": [], "isperson": 1},
        {"id": "5ee796b76a972816614e28b4", "customId": None, "name": "SALVADOR ALBALADEJO VIVANCOS",
         "code": "22442086C", "tradeName": 0, "email": "correo@salvadoralbaladejo.com", "mobile": "",
         "phone": "968352093", "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000021, "name": "SALVADOR ALBALADEJO VIVANCOS"},
         "billAddress": {"address": "AVD SAN JUAN DE LA CRUZ,5", "city": "Murcia", "postalCode": "30011",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.salvadoralbaladejo.com"},
         "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 1},
        {"id": "5ea73ba66a972805894c7c06", "customId": None, "name": "CLEVERBRIDGE AG", "code": "244822460",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 41000005, "name": "CLEVERBRIDGE AG"},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Alemania",
                         "countryCode": "DE", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5faab04e8d61f060ad034c96", "customId": None, "name": "GABRIEL AGUAYO ALBASINI", "code": "27435065K",
         "tradeName": 0, "email": "malu.notarioaguayo@notin.net", "mobile": "", "phone": "", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000041, "name": "GABRIEL AGUAYO ALBASINI"},
         "billAddress": {"address": "PLAZA CONDESTAVLE 5 ENTR. IZQ.", "city": "MURCIA", "postalCode": "30029",
                         "province": "ES-Espa\u00f1a", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.notariosenmurcia.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 1},
        {"id": "5eeb5d376a97280fa1226fe8", "customId": None, "name": "FRANCISCO JAVIER SERRANO ZAMORA",
         "code": "27476378A", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000010, "name": "FRANCISCO JAVIER SERRANO  ZAMORA"},
         "billAddress": {"address": "CAMINO DEL CONVENTO, 6", "city": "SANTOMERA", "postalCode": "30140",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 1},
        {"id": "5fbbf77572d48b3a5f4b1cce", "customId": None, "name": "SASU PURE GAMING", "code": "27521821884",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "",
         "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Francia",
                         "countryCode": "FR", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbfa76070b1c3be510565a", "customId": None, "name": "SYNLUCK GMBH", "code": "302090144",
         "tradeName": 0, "email": "sales@fintie.de", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Alemania",
                         "countryCode": "DE", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbf84156cd7f35ad7ca9c0", "customId": None, "name": "DOC MICRO", "code": "31429956451", "tradeName": 0,
         "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Francia",
                         "countryCode": "FR", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbf9302812805bb734ec06", "customId": None, "name": "NEMT NEUSCHAEFER EURO MULTI TRADE GMBH",
         "code": "41818945628", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Francia",
                         "countryCode": "FR", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5f8f1ea812e985290f4155a6", "customId": None, "name": "FRANCISCO JAVIER MATEOS P\u00c9REZ",
         "code": "48401513Z", "tradeName": 0, "email": "fran.mateos@onmi.es", "mobile": "", "phone": "",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000036, "name": "FRANCISCO JAVIER MATEOS PEREZ"},
         "billAddress": {"address": "PLAZA CONDESTABLE, 5, ESCALERA DERECHA, ENTRESUELO DERECHA", "city": "MURCIA",
                         "postalCode": "30008", "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 1},
        {"id": "5e697cec6a97282a6b073cfe", "customId": None, "name": "JOS\u00c9 ANTONIO FRUTOS ILL\u00c1N",
         "code": "48510216L", "tradeName": "(DISFRUTART)", "email": "info@disfruart.com", "mobile": "629549964",
         "phone": "", "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000006, "name": "Jose Antonio Frutos Ill\u00e1n"},
         "billAddress": {"address": "C\/ ACEQUIA DE ALGUAZAS, 191", "city": "MURCIA", "postalCode": "30012",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.disfruart.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 1},
        {"id": "5f55ff0d969a004d6a33f843", "customId": None, "name": "JOS\u00c9 ANTONIO FRUTOS ILL\u00c1N",
         "code": "48510216L", "tradeName": "(ROTULADO.ES)", "email": "info@rotulado.es", "mobile": "629549964",
         "phone": "", "type": "", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000024, "name": "Jos\u00e9 Antonio Frutos Ill\u00e1n"},
         "billAddress": {"address": "C\/ ACEQUIA DE ALGUAZAS, 191", "city": "MURCIA", "postalCode": "30012",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "ROTULADO.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 1},
        {"id": "5ee765f46a9728440b547c03", "customId": None, "name": "RUB\u00c9N GONZ\u00c1LEZ JIM\u00c9NEZ",
         "code": "48614483G", "tradeName": 0, "email": "Limpamur@gmail.com", "mobile": "661788074", "phone": "",
         "type": "creditor", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000004, "name": "Ruben Gonz\u00e1lez Jimenez"},
         "billAddress": {"address": "C\/LUGO 2\u00ba 3\u00baC", "city": "Murcia", "postalCode": "30003",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 1},
        {"id": "5f7c459c00ca7e732f2273ff", "customId": None, "name": "PABLO MATEOS P\u00c9REZ", "code": "48699478Z",
         "tradeName": "KEINU", "email": "pablo@keinu.dev", "mobile": "", "phone": "630 123 036", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000032, "name": "Pablo Mateos P\u00e9rez"},
         "billAddress": {"address": "C\/ SIM\u00d3N GARC\u00cdA 32, 1 AB", "city": "MURCIA", "postalCode": "30003",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 1},
        {"id": "5fbbf6283f548c0e5734f531", "customId": None, "name": "ANKER TECHNOLOGY (UK) LTD", "code": "5263181214",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "",
         "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Polonia",
                         "countryCode": "PL", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbc04a928243120172a904f", "customId": None, "name": "AGUSTIN GILGADO QUINTANA", "code": "70054674D",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000045, "name": "AGUSTIN GILGADO QUINTANA"},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Espa\u00f1a",
                         "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 1},
        {"id": "5fbbf8a154336c1a770960d3", "customId": None, "name": "AMAZON EU SARL, UK BRANCH", "code": "727255821",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "",
         "clientRecord": 0, "supplierRecord": {"num": 40000046, "name": "AMAZON EU SARL, UK BRANCH"},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Reino Unido",
                         "countryCode": "GB", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5f082c57b9e40c308d4ab1a9", "customId": None, "name": "BARTOLOM\u00c9 GIN\u00c9S GUIRADO NAVARRO",
         "code": "77707105H", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000012, "name": "BARTOLOME GINES GUIRADO NAVARRO"},
         "billAddress": {"address": "C\/ ANTONIO DE ULLOA 6", "city": "MURCIA", "postalCode": "300007",
                         "province": "MURCIA", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72ac"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 1},
        {"id": "5f18183d6656a274736b746a", "customId": None, "name": "EL CORTE INGLES, S.A.", "code": "A28017895",
         "tradeName": 0, "email": "comunicacionelcorteingles@elcorteingles.es", "mobile": "", "phone": "914018500",
         "type": "creditor", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000015, "name": "EL CORTE INGLES SA"},
         "billAddress": {"address": "CALLE HERMOSILLA, 112", "city": "MADRID", "postalCode": "28009",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72ac"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.elcorteingles.es"},
         "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5f898bce5458ca687f47ed46", "customId": None, "name": "SEB PROFESSIONAL IBERIA, S.A.",
         "code": "A28167138", "tradeName": 0, "email": "info@wmf.es", "mobile": "", "phone": "913580676",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000035, "name": "SEB PROFESSIONAL IBERIA SA."},
         "billAddress": {"address": "AVENIDA LLANO CASTELLANO, 15", "city": "MADRID", "postalCode": "28034",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.wmf.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5e6e5c6f6a97286c32178eb0", "customId": None, "name": "GRANDES ALMACENES FNAC ESPA\u00d1A, S.A.",
         "code": "A80500200", "tradeName": 0, "email": "recursoshumanos@fnac.es", "mobile": "", "phone": "917689100",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000014, "name": "GRANDES ALMACENES FNAC ESPA\u00d1A SA"},
         "billAddress": {"address": "PASEO DE LA FINCA, 1 - BL 11 PL 2", "city": "POZUELO DE ALARCON",
                         "postalCode": "28223", "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.fnac.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5ea739896a97286e3227811b", "customId": None, "name": "SIEMENS RENTING, S.A.", "code": "A81440786",
         "tradeName": 0, "email": "srenting.contabilidad.es@siemens.com", "mobile": "", "phone": "915148000",
         "type": "creditor", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000003, "name": "SIEMENS RENTING SA"},
         "billAddress": {"address": "RONDA DE EUROPA, 5", "city": "TRES CANTOS", "postalCode": "28760",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.siemens.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5f72e686892bb91c721ff338", "customId": None, "name": "XFERA MOVILES SAU", "code": "A82528548",
         "tradeName": 0, "email": "recepcion@yoigo.com", "mobile": "", "phone": "916588003", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000026, "name": "XFERA MOVILES SAU"},
         "billAddress": {"address": "AVENIDA DE BRUSELAS, 38", "city": "ALCOBENDAS", "postalCode": "28108",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.yoigo.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5ea7390c6a972870ef4edfd4", "customId": None, "name": "INER ENERG\u00cdA CASTILLA LA MANCHA, S.L.",
         "code": "B02494375", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000002, "name": "Iner Energ\u00eda Castilla la Mancha, S.L."},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Espa\u00f1a",
                         "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fa164b4d5a28124f52c8e84", "customId": None, "name": "APR ALBACETE 2012 SOCIEDAD LIMITADA.",
         "code": "B02533172", "tradeName": 0, "email": "pgarcia@benotac.es", "mobile": "", "phone": "",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000039, "name": "APR ALBACETE 2012 SOCIEDAD LIMITADA."},
         "billAddress": {"address": "C\/ MAYOR, 20 - BJ IZ", "city": "ALBACETE", "postalCode": "02001",
                         "province": "Albacete", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5e69832a6a97284d482625a9", "customId": None, "name": "YESOS PROYECTADOS J. ANDRES, S.L.",
         "code": "B05528567", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000011, "name": "YESOS PROYECTADOS J. ANDRES, SOCIEDAD LIMITADA."},
         "billAddress": {"address": "C\/ TABLACHO MORENO, 32", "city": "MURCIA", "postalCode": "30163",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5ec56df36a9728415a51e4cb", "customId": None, "name": "ONMI DESIGN, S.L.", "code": "B05556873",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000018, "name": "ONMI DESIGN S.L."},
         "billAddress": {"address": "PLAZA CONDESTABLE, 5", "city": "MURCIA", "postalCode": "30009",
                         "province": "MURCIA", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbcf8b78e6f5e794f2a9af8", "customId": None, "name": "ONMI LINK TEAMS SL.", "code": "B05561840",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000049, "name": "ONMI LINK TEAMS SL."},
         "billAddress": {"address": "PLAZA CONDESTABLE, 5 - ESC DR ENTRESUE DR", "city": "MURCIA",
                         "postalCode": "30009", "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5ee791f26a97282c587df25e", "customId": None, "name": "ONMI CONSULTING TEAMS, S.L.", "code": "B05563044",
         "tradeName": 0, "email": "onmi.consulting@holdedbox.com", "mobile": "", "phone": "", "type": "creditor",
         "iban": "", "swift": "", "groupId": "", "clientRecord": {"num": 43000001, "name": "ONMI CONSULTING TEAMS,SL."},
         "supplierRecord": {"num": 40000019, "name": "ONMI CONSULTING TEAMS"},
         "billAddress": {"address": "C\/ CONDESTABLE 5, ESC DHA, ENTLO DCHA", "city": "Murcia", "postalCode": "30009",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72b5"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5f75792bac4b326f503bb70d", "customId": None, "name": "ONMI LAW TEAMS, S.L.", "code": "B05568100",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000028, "name": "ONMI LAW TEAMS SL."},
         "billAddress": {"address": "AVENIDA LIBERTAD (SAN MIGUEL), 5 - PISO 1 AB", "city": "MURCIA",
                         "postalCode": "30009", "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5ef998536a97281b5948ab33", "customId": None, "name": "MANUFACTURAS MURCIAS, S.L.", "code": "B30030456",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 41000011, "name": "MANUFACTURAS MURCIA SL"},
         "billAddress": {"address": "SAGASTA 35", "city": "MURCIA", "postalCode": "30005", "province": "Murcia",
                         "country": "Espa\u00f1a", "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72ac"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5e69847e6a97284d0a4da568", "customId": None, "name": "AG AZUL GRES, S.L.", "code": "B30076160",
         "tradeName": 0, "email": "azulgres@azul-gres.com", "mobile": "", "phone": "968307600", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000013, "name": "AZUL GRES SL"},
         "billAddress": {"address": "AVENIDA TENIENTE MONTESINOS, 6", "city": "MURCIA", "postalCode": "30100",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.azul-gres.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5faceff45ab1ab5ec1211378", "customId": None, "name": "COMERCIAL GOMEZ MAYOR, S.L.", "code": "B30442362",
         "tradeName": 0, "email": "gomezmayor@outlook.com", "mobile": "", "phone": "868000072", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000042, "name": "COMERCIAL GOMEZ MAYOR S.L."},
         "billAddress": {"address": "CNO. VIEJO DE ABANILLA S\/N CABEZO DE TORRES", "city": "MURCIA",
                         "postalCode": "30110", "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5ea73c7a6a972812c255a234", "customId": None, "name": "PRODUCTOS CONTINENTAL, S.L.", "code": "B30444285",
         "tradeName": 0, "email": "salzillo@cafes-salzillo.es", "mobile": "", "phone": "968261212", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000016, "name": "PRODUCTOS CONTINENTAL SL"},
         "billAddress": {"address": "CARRETERA N-340-A (AV MURCIA), 106", "city": "MURCIA", "postalCode": "30166",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.cafes-salzillo.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5f7b2dc6f46d3b69ab3ade70", "customId": None, "name": "MOSCA-MARITIMO, S.L.", "code": "B30464721",
         "tradeName": 0, "email": "elmosca@elmosca.es", "mobile": "", "phone": "968389111", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000031, "name": "MOSCA-MARITIMO SL"},
         "billAddress": {"address": "CARRETERA DE MADRID (MOLINA DE SEGURA), 376", "city": "", "postalCode": "",
                         "province": "", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.elmosca.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5ee799d86a97285f02008a92", "customId": None, "name": "ALSIMUR, S.L.", "code": "B30550578",
         "tradeName": 0, "email": "administracion@alsimur.es", "mobile": "", "phone": "968848140", "type": "creditor",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000008, "name": "ALSIMUR,SL."},
         "billAddress": {"address": "CTRA SANTA CATALINA, 10", "city": "MURCIA", "postalCode": "30012",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e7271"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.alsimur.es"}, "tags": [],
         "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5e697d3e6a97282dbe7d017b", "customId": None, "name": "BALLESTER Y BARNES, S.L.", "code": "B30715668",
         "tradeName": 0, "email": "info@ballesterybarnes.com", "mobile": "", "phone": "968135155", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000007, "name": "BALLESTER Y BARNES SL"},
         "billAddress": {"address": "C\/ MINA DICHOSA, NAVE H 11", "city": "LA UNION", "postalCode": "30360",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.ballesterybarnes.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5ee8bb366a97282a3d6e71c6", "customId": None, "name": "GISPERT BUSINESS, S.L.", "code": "B30811814",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000022, "name": "GISPERT BUSINESS SL"},
         "billAddress": {"address": "C\/AMANECER 22 NAVE B6 P.I.OESTE", "city": "MURCIA", "postalCode": "30169",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e7258"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5e697ba46a97282e76600914", "customId": None, "name": "INGENIERIA Y CONSTRUCCIONES CUBER, S.L.",
         "code": "B30894042", "tradeName": 0, "email": "bernalliarteantonio@gmail.com", "mobile": "", "phone": "",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000003, "name": "INGENIERIA Y CONSTRUCCIONES CUBER SOCIEDAD LIMITADA."},
         "billAddress": {"address": "C\/ OSLO, 13 - 1 NAV 8", "city": "CARTAGENA", "postalCode": "30353",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0}, {"id": "5ea73d826a9728280630ecbd", "customId": None, "name": "SAINT GOBAIN SANIPLUS, S.L.U.",
                          "code": "B33660440", "tradeName": 0, "email": "", "mobile": "", "phone": "",
                          "type": "creditor", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
                          "supplierRecord": {"num": 41000007, "name": "SAINT GOBAIN SANIPLUS, S.L.U."},
                          "billAddress": {"address": "", "city": "EL PALMAR", "postalCode": "", "province": "",
                                          "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
                          "customFields": [],
                          "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0,
                                       "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                                       "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""},
                          "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5e697d956a97282dbd38d309", "customId": None, "name": "OLTRA PUJANTE, S.L.", "code": "B54678222",
         "tradeName": 0, "email": "ieoltrasl@hotmail.com", "mobile": "", "phone": "865513875", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000008, "name": "OLTRA PUJANTE SL."},
         "billAddress": {"address": "C\/ PIO V, 23 - AC", "city": "ORIHUELA", "postalCode": "03300",
                         "province": "Alicante", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5e697b626a972818185d559b", "customId": None, "name": "LA VEGA TRADE, S.L.", "code": "B54958574",
         "tradeName": 0, "email": "lavegatrade@gmail.com", "mobile": "", "phone": "", "type": "supplier", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000002, "name": "La Vega Trade, S.L."},
         "billAddress": {"address": "", "city": "ROJALES", "postalCode": "03170", "province": "Alicante",
                         "country": "Espa\u00f1a", "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5f72ee137fce7764be0c8b75", "customId": None, "name": "HOLDED TECHNOLOGIES, S.L.", "code": "B66543778",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000027, "name": "HOLDED TECHNOLOGIES SL."},
         "billAddress": {"address": "C\/ PROVEN\u00c7A, 275 - P. 4 PTA. 1", "city": "BARCELONA", "postalCode": "08037",
                         "province": "Barcelona", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.holded.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5ea737a06a972859ed47c8fa", "customId": None, "name": "LEGISMARK, S.L.U.P", "code": "B73019937",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 41000001, "name": "Legismark, S.L.U.P"},
         "billAddress": {"address": "", "city": "Murcia", "postalCode": "30009", "province": "Murcia",
                         "country": "Espa\u00f1a", "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0}, {"id": "5f75a6e31aa22260b21a7f3d", "customId": None,
                          "name": "ASECOM ASESORIA FISCAL Y LABORAL SOCIEDAD LIMITADA.", "code": "B73148694",
                          "tradeName": 0, "email": "", "mobile": "", "phone": "968221243", "type": "supplier",
                          "iban": "", "swift": "", "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000029,
                                                                                                        "name": "ASECOM ASESORIA FISCAL Y LABORAL SOCIEDAD LIMITADA."},
                          "billAddress": {"address": "C\/ ESCULTOR ROQUE LOPEZ (SAN MIGUEL), 5 - 1 G", "city": "MURCIA",
                                          "postalCode": "30008", "province": "Murcia", "country": "Espa\u00f1a",
                                          "countryCode": "ES", "info": ""}, "customFields": [],
                          "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0,
                                       "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                                       "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""},
                          "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5ee795366a972870df3db7ef", "customId": None, "name": "GRUPO RM MARCOS, S.L.", "code": "B73290561",
         "tradeName": 0, "email": "rotulosmarcos@rotulosmarcos.com", "mobile": "", "phone": "902929394",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000020, "name": "GRUPO RM MARCOS,SL."},
         "billAddress": {"address": "C\/ AMISTAD (PG INDUSTRIAL OESTE), 19 - NAV A 3", "city": "MURCIA",
                         "postalCode": "30169", "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.rotulosmarcos.com"},
         "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5ea754446a97281c772ef123", "customId": None, "name": "PC COMPONENTES Y MULTIMEDIA SLU",
         "code": "B73347494", "tradeName": 0, "email": "info@pccomponenetes.com", "mobile": "", "phone": "968977977",
         "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000017, "name": "PC COMPONENTES Y MULTIMEDIA SLU"},
         "billAddress": {"address": "AVENIDA DE EUROPA", "city": "ALHAMA DE MURCIA", "postalCode": "30840",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.pccomponentes.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5e6983646a9728510e0666c4", "customId": None, "name": "CARPINTERIA PACO GIL, S.L.", "code": "B73623324",
         "tradeName": 0, "email": "carpaco@carpaco.es", "mobile": "", "phone": "968350487", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000012, "name": "CARPINTERIA PACO GIL SL"},
         "billAddress": {"address": "CAMINO FUENSANTA, 258", "city": "MURCIA", "postalCode": "30012",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5eea35936a972871a951d3f9", "customId": None, "name": "IMPORTACIONES TECNOLOGICAS DEL SURESTE, S.L.",
         "code": "B73664054", "tradeName": 0, "email": "info@itds.es", "mobile": "", "phone": "968909023",
         "type": "creditor", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000009, "name": "IMPORTACIONES TECNOLOGICAS DEL SURESTE"},
         "billAddress": {"address": "AVENIDA JUAN RAMON JIMENEZ, 1", "city": "CALASPARRA", "postalCode": "30420",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72ac"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.itds.es"}, "tags": [],
         "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5e697c056a97282f306dcfdd", "customId": None, "name": "IMOTEC DOMOTICA, S.L.", "code": "B73701500",
         "tradeName": 0, "email": "comercial@imotec.es", "mobile": "", "phone": "968967432", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000004, "name": "IMOTEC DOMOTICA SL"},
         "billAddress": {"address": "C\/ OLOF PALME, 9 - ESC 1. PISO 1 B", "city": "MURCIA", "postalCode": "30009",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.imotec.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5ea7370a6a97285cab2408e2", "customId": None, "name": "ALEPAR AUTOMATISMOSs, S.L.U.",
         "code": "B73873515", "tradeName": 0, "email": "administracion@aleparautomatismos.com", "mobile": "",
         "phone": "968277187", "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000015, "name": "Alepar Automatismos, S.L.U."},
         "billAddress": {"address": "AVDA. DE LA CEBADA 49B", "city": "Murcia", "postalCode": "30163",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5ea73ce56a97281ee01e98f9", "customId": None, "name": "TELECOMUNICACIONES Y FARMACIA, S.L.",
         "code": "B73874703", "tradeName": "HEALTH & PHARMA", "email": "", "mobile": "", "phone": "",
         "type": "creditor", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000006, "name": "TELECOMUNICACIONES Y FARMACIA, S.L."},
         "billAddress": {"address": "C\/ SAN JORGE 1", "city": "Murcia", "postalCode": "30120", "province": "Murcia",
                         "country": "Espa\u00f1a", "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5e697f046a972833b6181808", "customId": None, "name": "VPROYECTA OFICINAS, S.L.", "code": "B73887127",
         "tradeName": 0, "email": "info@vproyectaoficinas.com", "mobile": "", "phone": "968076225", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000009, "name": "VPROYECTA OFICINAS SL"},
         "billAddress": {"address": "C\/ CARRIL CHORNOS, 11 - C", "city": "MURCIA", "postalCode": "30009",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.vproyectaoficinas.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0}, {"id": "5f89479fc135f069b03bac15", "customId": None,
                                                   "name": "PARAFARMACIA CONDESTABLE, SOCIEDAD DE RESPONSABILIDAD LIMITADA.",
                                                   "code": "B73955890", "tradeName": 0,
                                                   "email": "contabilidad@farmaciamurcia24h.com", "mobile": "",
                                                   "phone": "", "type": "supplier", "iban": "", "swift": "",
                                                   "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000034,
                                                                                                        "name": "PARAFARMACIA CONDESTABLE, SOCIEDAD DE RESPONSABILIDAD LIMITADA."},
                                                   "billAddress": {"address": "C\/ CONDESTABLE, 2 - BJ",
                                                                   "city": "MURCIA", "postalCode": "30009",
                                                                   "province": "Murcia", "country": "Espa\u00f1a",
                                                                   "countryCode": "ES", "info": ""}, "customFields": [],
                                                   "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0,
                                                                "paymentDay": 0, "paymentMethod": 0, "discount": 0,
                                                                "language": "es", "currency": "eur", "salesTax": [],
                                                                "purchasesTax": []}, "socialNetworks": {"website": ""},
                                                   "tags": [], "notes": [], "contactPersons": [],
                                                   "shippingAddresses": [], "isperson": 0},
        {"id": "5e6980616a97283fcd7a2054", "customId": None, "name": "PINTURAS MORATALLA, S.L.", "code": "B73973364",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000010, "name": "PINTURAS MORATALLA, SOCIEDAD LIMITADA."},
         "billAddress": {"address": "C\/ HUMANISTA ALONSO SANCHEZ, 2 - PISO 2 I", "city": "MORATALLA",
                         "postalCode": "30440", "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES",
                         "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5f0840f2acf8d90ed322b0e2", "customId": None, "name": "SAN LORENZO FLORISTAS, S.L.", "code": "B73980385",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 41000014, "name": "SAN LORENZO FLORISTAS  SL"},
         "billAddress": {"address": "C\/ ALEJANDRO SEIQUER , 10", "city": "Murcia", "postalCode": "30001",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5f55fc2f8914a66ec66a1522", "customId": None, "name": "AGUAPURA AGUAVIVA, S.L.", "code": "B81804643",
         "tradeName": 0, "email": "info@waterlogic.es", "mobile": "", "phone": "913044011", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000023, "name": "AGUAPURA AGUAVIVA SL"},
         "billAddress": {"address": "C\/ MEDEA, 4 - 1\u00ba B", "city": "MADRID", "postalCode": "28037",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.waterlogic.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5f76edddb6217744e429376e", "customId": None, "name": "AMAZON SPAIN SERVICES SL.", "code": "B84570936",
         "tradeName": 0, "email": "comercial@buyvip.com", "mobile": "", "phone": "910484500", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000030, "name": "AMAZON SPAIN SERVICES SL."},
         "billAddress": {"address": "C\/ RAMIREZ DE PRADO, 5", "city": "MADRID", "postalCode": "28045",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.buyvip.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5fbbf5856fc51b20ee551b60", "customId": None, "name": "OLD PLAY SPAIN, S.L.", "code": "B94059367",
         "tradeName": 0, "email": "info@oldplayspain.es", "mobile": "", "phone": "", "type": "supplier", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "POLIGONO INDUSTRIAL CASTI\u00d1EIRAS, 28", "city": "BUEU", "postalCode": "36930",
                         "province": "Pontevedra", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.opirata.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5e697aa56a97281b266f0c05", "customId": None, "name": "ALUMINIOS ALUFUENTES C.B.", "code": "E30910194",
         "tradeName": 0, "email": "alufuentes57@gmail.com", "mobile": "696636762", "phone": "", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000001, "name": "ALUMINIOS ALUFUENTES C.B."},
         "billAddress": {"address": "C\/ ARIAS, 27 - DOLORES 1 A", "city": "CARTAGENA", "postalCode": "30310",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fa445197d7318660d2c0534", "customId": None, "name": "EL BOTIJERO SAN ANTON", "code": "E73659922",
         "tradeName": 0, "email": "", "mobile": "636645332", "phone": "", "type": "supplier", "iban": "", "swift": "",
         "groupId": "", "clientRecord": 0, "supplierRecord": {"num": 40000040, "name": "EL BOTIJERO SAN ANTON"},
         "billAddress": {"address": "C\/ SAN ANT\u00d3N  S\/N Bajo", "city": "MURCIA", "postalCode": "30009",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5f2bc6db1b6c7a6c71088763", "customId": None, "name": "VIVEROS MURCIA S.C.", "code": "F30393961",
         "tradeName": 0, "email": "info@viverosmurcia.com", "mobile": "", "phone": "968853089", "type": "creditor",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000016, "name": "VIVEROS MURCIA SC"},
         "billAddress": {"address": "CAMINO IMOBILIARIA S\/N", "city": "MURCIA", "postalCode": "30163",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.viverosmurcia.com"},
         "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5e697c406a9728325614d8a2", "customId": None, "name": "FLARELUX S.C.", "code": "F73893471",
         "tradeName": 0, "email": "info@flarelux.com", "mobile": "", "phone": "968710810", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000005, "name": "FLARELUX S.C."},
         "billAddress": {"address": "AVENIDA ALICANTE (MURCIA), 137 - BAJO", "city": "MURCIA", "postalCode": "30007",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": "www.flarelux.com"},
         "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5f08340977608f3d69691e53", "customId": None, "name": "MICROSOFT IRELAND OPERATIONS LTD",
         "code": "N0071290A", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "creditor", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 41000013, "name": "MICROSOFT IRELAND "},
         "billAddress": {"address": "PASEO DEL CLUB DEPORTIVO, 1", "city": "POZUELO DE ALARCON", "postalCode": "28223",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": {"$oid": "5e67c91d6a97281d714e72bb"}, "dueDays": 0,
                      "paymentDay": 0, "paymentMethod": 0, "discount": 0, "language": "es", "currency": "eur",
                      "salesTax": [], "purchasesTax": []}, "socialNetworks": {"website": ""}, "tags": [], "notes": [],
         "contactPersons": [], "shippingAddresses": [], "isperson": 0},
        {"id": "5f85b9e97b64bd794449865f", "customId": None, "name": "APPLE DISTRIBUTION INTERNATIONAL",
         "code": "N0072469J", "tradeName": 0, "email": "contactus.es@euro.apple.com", "mobile": "",
         "phone": "900150503", "type": "supplier", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000033, "name": "APPLE DISTRIBUTION INTERNATIONAL"},
         "billAddress": {"address": "PLAZA LEALTAD, 4", "city": "MADRID", "postalCode": "28014", "province": "Madrid",
                         "country": "Espa\u00f1a", "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.apple.com"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5fbbf9fef9a30a05647eef88", "customId": None, "name": "BTA POWER TECHNOLOGY", "code": "N4000201F",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "",
         "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Espa\u00f1a",
                         "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbfaa55edc1241da1883c4", "customId": None, "name": "HONG KONG UGREEN LIMITED", "code": "N7203066A",
         "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "", "swift": "", "groupId": "",
         "clientRecord": 0, "supplierRecord": {"num": 40000043, "name": "HONG KONG UGREEN LIMITED"},
         "billAddress": {"address": "CALLE MARCELO USERA, 60 - 1 C", "city": "MADRID", "postalCode": "28026",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbf6c5f00e9867c7756293", "customId": None, "name": "CHENG DU YI MEI JIN KE JI LIMITED",
         "code": "N7204756F", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Espa\u00f1a",
                         "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5f9a7c4e3ca13e4bab58ad5c", "customId": None, "name": "SHENZHENSHI LIANGCHENGJIYE TECHNOLOGY CO LTD",
         "code": "N7205292A", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "supplier", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000038, "name": "Shenzhenshi Liangchengjiye Technology Co LTD"},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Espa\u00f1a",
                         "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbf7c890c82636985af617", "customId": None, "name": "SHENZHEN SHI YULE KEJI YOUXIAN GONGSI",
         "code": "N7205531B", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000048, "name": "SHENZHEN SHI YULE KEJI YOUXIAN GONGSI"},
         "billAddress": {"address": "", "city": "", "postalCode": "", "province": "", "country": "Espa\u00f1a",
                         "countryCode": "ES", "info": ""}, "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fbbf98a6e6db5688f50cf8a", "customId": None, "name": "HONGKONG STAROC TECHNOLOGY CO LIMITED",
         "code": "N7401426G", "tradeName": 0, "email": "", "mobile": "", "phone": "", "type": "", "iban": "",
         "swift": "", "groupId": "", "clientRecord": 0, "supplierRecord": 0,
         "billAddress": {"address": "CALLE MARQUES DE CAMPO, 16 - 1 3", "city": "DENIA", "postalCode": "03700",
                         "province": "Alicante", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 0},
        {"id": "5fb7b718ca8067632247daab", "customId": None, "name": "AMAZON EU SARL SUCURSAL EN ESPA\u00d1A.",
         "code": "W0184081H", "tradeName": 0, "email": "prensa-amazon@tinkle.es", "mobile": "", "phone": "910484500",
         "type": "", "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000044, "name": "AMAZON EU SARL SUCURSAL EN ESPA\u00d1A."},
         "billAddress": {"address": "CALLE RAMIREZ DE PRADO, 5", "city": "MADRID", "postalCode": "28045",
                         "province": "Madrid", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": "www.amazon.es"}, "tags": [], "notes": [], "contactPersons": [],
         "shippingAddresses": [], "isperson": 0},
        {"id": "5f9001f2c0f2c538c5092ae6", "customId": None, "name": "MATIAS LEONARDO MEZA SUARES", "code": "X6441044D",
         "tradeName": 0, "email": "mtsarg@gmail.com", "mobile": "", "phone": "629723533 ", "type": "supplier",
         "iban": "", "swift": "", "groupId": "", "clientRecord": 0,
         "supplierRecord": {"num": 40000037, "name": "MATIAS LEONARDO MEZA SUARES"},
         "billAddress": {"address": "C\/ BATALLA DE LAS FLORES, 1 1\u00baG", "city": "MURCIA", "postalCode": "30008",
                         "province": "Murcia", "country": "Espa\u00f1a", "countryCode": "ES", "info": ""},
         "customFields": [],
         "defaults": {"salesChannel": 0, "expensesAccount": 0, "dueDays": 0, "paymentDay": 0, "paymentMethod": 0,
                      "discount": 0, "language": "es", "currency": "eur", "salesTax": [], "purchasesTax": []},
         "socialNetworks": {"website": ""}, "tags": [], "notes": [], "contactPersons": [], "shippingAddresses": [],
         "isperson": 1}]
read_json(json)
